### ISSUE TITLE
some problems when installing

### ISSUE THREAD

**Issue by xmubingo** [wanji/caffe-sl#13]
hi wanji,
thanks for sharing code with us, and the code is very professional and clear.
1. in README

`# get the MNIST dataset
./data/mnist/get_data.sh`
===>**get_mnist.sh**
2. in examples/mnist_sl/generate_batch.py

`#import ipdb`
ipdb is not very commonly used.

3.in generate_triplet.py
line 83:  if pos != label:
===> if pos != qry:

thanks.

**Comment by wanji** [comment]
fixed, thanks
