### ISSUE TITLE
Pairwise Ranking using caffe-sl

### ISSUE THREAD

**Issue by iqbalnaved** [wanji/caffe-sl#8]
Hi,

I would like to know if it possible to setup a pairwise ranking model using caffe-sl. I am trying to use a model similar to the one described in the paper: 
Wang, Jiang, et al. "Learning Fine-grained Image Similarity with Deep Ranking."

But I want to rank face images based on some specific sets of criteria. I have seen that you have a loss function for this. But I am not sure how to set up the prototxt file. If you could give an example that would be quite helpful. Looking forward to you reply.

Thanks,

Naved

**Comment by wanji** [comment]
Please refer to `examples/mnist_sl` for example.
